<?php



require plugin_dir_path( __FILE__ ) . 'model.php';

$authors = getAllAuthors();


require plugin_dir_path(__FILE__) . 'class-authors-list.php';

$list = new Authors_List();
?>


<div class="wrap">
    <h2>WP_List_Table Class Example</h2>

    <div id="poststuff">
        <div id="post-body" class="metabox-holder columns-2">
            <div id="post-body-content">
                <div class="meta-box-sortables ui-sortable">
                    <form method="post">
                        <?php
                        $list->prepare_items();
                        $list->display(); ?>
                    </form>
                </div>
            </div>
        </div>
        <br class="clear">
    </div>
</div>


  <?php echo Formbuilder::addInput("firstname", "text", "author-input", "firstname-input", "First Name"); ?>
  <?php echo Formbuilder::addInput("lastname", "text", "author-input", "lastname-input", "Last Name"); ?>
  <?php echo Formbuilder::addInput("submit", "submit", "author-button", "submit_authors", null, "Submit"); ?>
