<?php


require plugin_dir_path(__FILE__) . 'class-verlage-list.php';

$list = new Verlage_List();


?>


<div class="wrap">
    <h2>Verlage <a href="admin.php?page=create&mode=verlaege" class="page-title-action">Erstellen</a></h2>

    <div id="poststuff">
        <div id="post-body" style="width:100%" class="metabox-holder columns-2">
            <div id="post-body-content">
                <div class="meta-box-sortables ui-sortable">
                    <form method="post">
                        <?php
                        $list->prepare_items();
                        $list->display(); ?>
                    </form>
                </div>
            </div>
        </div>
        <br class="clear">
    </div>
</div>
