<?php


function articlesShortcode(){
    $site = isset($_POST['articles']) ? $_POST['articles'] : 1;
    $articles = getArticles($site === 1 ? 0 : ($site*5) - 5, 5);
    $amount = intval(getArticlesEntryAmount());
    ?>
    <h3><?php echo _e('Articles')?></h3>
<div class="articles-viewer">
    <ul class="articles-list" data-site-amount="<?php echo getArticlesEntryAmount(); ?>">
        <?php foreach($articles as $art): ?>
        <li class="article-list-item">
            <div class="list-img"><img src="<?php echo $art['thumbnail_url'] === "" ? "https://btp.at/btp-content/uploads/2017/08/pdf_sujet.jpg" : $art['thumbnail_url'] ?>" alt=""></div>
            <div class="list-content">
                <p><a href="<?php echo $art['url'] ?>"><?php echo $art['title']; ?></a></p>
                <small><i><?php echo $art['author_title'].'. ' . $art['firstname'] . ' ' . $art['lastname'] ?>, <?php echo $art['verlag'] ?>, <?php echo $art['date'] ?></i></small>
            </div>
        </li>
            <hr>

        <?php endforeach; ?>
    </ul>
    <a class="article-pagination-btn dashicons dashicons dashicons-arrow-left-alt <?php echo count($articles) < 5 ? 'hidden' : '' ?>" id="ap-start" data-site="1"></a>
    <a class="article-pagination-btn dashicons dashicons-arrow-left-alt2 hidden" id="ap-prev" data-site=""></a>
    <span id="articles-page-indicator"></span>
    <a class="article-pagination-btn dashicons dashicons-arrow-right-alt2 <?php echo $amount < 5 ? 'hidden' : '' ?>" id="ap-next" data-site="<?php echo $amount > 5 ? '2' : '' ?>"></a>
    <a class="article-pagination-btn dashicons dashicons dashicons-arrow-right-alt <?php echo $amount < 5 ? 'hidden' : '' ?>" id="ap-end" data-site="<?php echo ceil(getArticlesEntryAmount() / 5); ?>"></a>

</div>

<?php
}
//
/*   <a class="article-pagination-btn" data-site="<?php echo $site === 1 ? 1 : $site - 1 ?>">previous site</a>*/
/*    <a class="article-pagination-btn" data-site="<?php echo $site + 1 ?>">next site</a>*/
?>
