<?php


function booksShortcode(){
    $books = getAllBooks();
    ?>
    <h3><?php echo _e('Books')?></h3>
<div class="books-viewer">
  <div class="book-items-wrapper <?php echo count($books) > 0 ? "books-not-empty" : "books-empty" ?>">
    <?php foreach($books as $book):?>
    <div class="book-item">
        <a target="_blank" href="<?php echo $book['url'] ?>"><img src="<?php echo $book['thumbnail_url'] === "" ? "https://btp.at/btp-content/uploads/2018/03/Der-Geschaeftsfuehrer.jpg" : $book['thumbnail_url'] ?>" alt=""></a>
        <div class="book-item-content">
          <a target="_blank" href="<?php echo $book['url'] ?>"><h3><?php echo $book['title'] ?></h3></a>
          <p><?php echo _e('Edition'); ?> <?php echo $book['edition'] ?><br><?php echo $book['verlag'] ?><br><?php echo $book['lastname'] ?></p>
        </div>
      </div>
    <?php endforeach; ?>
  </div>
</div>

<?php
}
//
/*   <a class="article-pagination-btn" data-site="<?php echo $site === 1 ? 1 : $site - 1 ?>">previous site</a>*/
/*    <a class="article-pagination-btn" data-site="<?php echo $site + 1 ?>">next site</a>*/
?>
