<?php


function booksShortcode(){
    $books = getAllBooks();
    ?>
    <h3><?php echo _e('Books')?></h3>
<div class="books-viewer">
    <?php foreach($books as $book):?>
    <div class="book-item">
        <a href="<?php echo $book['url'] ?>"><img src="<?php echo $book['thumbnail_url'] === "" ? "https://btp.at/btp-content/uploads/2018/03/Der-Geschaeftsfuehrer.jpg" : $book['thumbnail_url'] ?>" alt=""></a>
        <a href="<?php echo $book['url'] ?>"><h5><?php echo $book['title'] ?></h5></a>
        <p><?php echo $book['edition'] ?><br><?php echo $book['verlag'] ?><br><?php echo $book['author_title'] ?></p>
    </div>
    <?php endforeach; ?>
</div>

<?php
}
//
/*   <a class="article-pagination-btn" data-site="<?php echo $site === 1 ? 1 : $site - 1 ?>">previous site</a>*/
/*    <a class="article-pagination-btn" data-site="<?php echo $site + 1 ?>">next site</a>*/
?>
