<?php


function lawyersShortcode(){
    ?>
    <a href="#">testsetset</a>
    <section class="lawyers-shortcode-wrapper" style="position: relative;">

            <?php
            $posts = get_posts(array(
                'posts_per_page'	=> -1,
                'post_type'			=> 'lawyers',
                'suppress_filters'  => 0,
                'meta_query' => array(
                    array(
                        'key' => 'position',
                        'value' => '11',
                        'compare' => 'LIKE'
                    )
                )
            ));
            if( $posts ): ?>
                <h1> <?php _e( 'Lawyers', 'btp-cm' ) ?> </h1>

                <div id="btp-team">
                    <?php foreach( $posts as $post ):
                        setup_postdata( $post );
                        ?>
                        <div class="lawyer-id-team">
                            <?php if( get_field('portrait', $post->ID) ): ?>
                            <a href='<?php echo get_the_permalink($post->ID); ?>'>
                                <img src="<?php the_field('portrait', $post->ID); ?>" />
                                <?php endif; ?>
                                <p class="lawyer-name-team">
                                    <?php the_field('vorname', $post->ID)?>
                                    <?php the_field('nachname', $post->ID) ?>
                                </p></a>
                            <?php
                            $position = get_field('position', $post->ID);
                            if( $position ): ?>
                                <p><?php echo $position->name; ?> </p>
                            <?php endif; ?>
                            <a href="mailto:<?php the_field('e-mail', $post->ID) ?>"><?php the_field('e-mail', $post->ID) ?></a>
                        </div>
                    <?php endforeach; ?>
                    <?php wp_reset_postdata(); ?>
                </div>
            <?php endif; ?>


            <?php
            $posts = get_posts(array(
                'posts_per_page'	=> -1,
                'post_type'			=> 'lawyers',
                'suppress_filters'  => 0,
                'meta_query' => array(
                    array(
                        'key' => 'position',
                        'value' => '12',
                        'compare' => 'LIKE'
                    )
                )
            ));



            if( $posts ): ?>
                <h1> <?php _e( 'Associates', 'btp-cm' ) ?> </h1>

                <div id="btp-team">
                    <?php foreach( $posts as $post ):
                        setup_postdata( $post );
                        ?>
                        <div class="lawyer-id-team">
                            <?php if( get_field('portrait', $post->ID) ): ?>
                            <a href=' <?php echo get_the_permalink($post->ID); ?>'>
                                <img src="<?php the_field('portrait', $post->ID); ?>" />
                                <?php endif; ?>
                                <p class="lawyer-name-team">
                                    <?php the_field('vorname', $post->ID)?>
                                    <?php the_field('nachname', $post->ID) ?>
                                </p></a>
                            <?php
                            $position = get_field('position', $post->ID);
                            if( $position ): ?>
                                <p><?php echo $position->name; ?> </p>
                            <?php endif; ?>
                            <a href="mailto:<?php the_field('e-mail', $post->ID) ?>"><?php the_field('e-mail', $post->ID) ?></a>
                        </div>
                    <?php endforeach; ?>
                    <?php wp_reset_postdata(); ?>
                </div>
            <?php endif; ?>


            <?php
            $posts = get_posts(array(
                'posts_per_page'	=> -1,
                'post_type'			=> 'lawyers',
                'suppress_filters'  => 0,
                'meta_query' => array(
                    array(
                        'key' => 'position',
                        'value' => '13',
                        'compare' => 'LIKE'
                    )
                )
            ));
            if( $posts ): ?>
                <h1> <?php _e( 'Experts', 'btp-cm' ) ?> </h1>

                <div id="btp-team">
                    <?php foreach( $posts as $post ):
                        setup_postdata( $post );
                        ?>
                        <div class="lawyer-id-team">
                            <?php if( get_field('portrait', $post->ID) ): ?>
                            <a href=' <?php echo get_the_permalink($post->ID); ?>'>
                                <img src="<?php the_field('portrait', $post->ID); ?>" />
                                <?php endif; ?>
                                <p class="lawyer-name-team">
                                    <?php the_field('vorname', $post->ID)?>
                                    <?php the_field('nachname', $post->ID) ?>
                                </p></a>
                            <?php
                            $position = get_field('position', $post->ID);
                            if( $position ): ?>
                                <p><?php echo $position->name; ?> </p>
                            <?php endif; ?>
                            <a href="mailto:<?php the_field('e-mail', $post->ID) ?>"><?php the_field('e-mail', $post->ID) ?></a>
                        </div>
                    <?php endforeach; ?>
                </div>
                <?php wp_reset_postdata(); ?>
            <?php endif; ?>


            <?php
            $posts = get_posts(array(
                'posts_per_page'	=> -1,
                'post_type'			=> 'lawyers',
                'suppress_filters'  => 0,
                'meta_query' => array(
                    array(
                        'key' => 'position',
                        'value' => '14',
                        'compare' => 'LIKE'
                    )
                )
            ));
            if( $posts ): ?>
                <h1> <?php _e( 'Backoffice', 'btp-cm' ) ?> </h1>

                <div id="btp-team">
                    <?php foreach( $posts as $post ):
                        setup_postdata( $post );
                        ?>
                        <div class="lawyer-id-team">
                            <?php if( get_field('portrait', $post->ID) ): ?>
                            <a href=' <?php echo get_the_permalink($post->ID); ?>'>
                                <img src="<?php the_field('portrait', $post->ID); ?>" />
                                <?php endif; ?>
                                <p class="lawyer-name-team">
                                    <?php the_field('vorname', $post->ID)?>
                                    <?php the_field('nachname', $post->ID) ?>
                                </p></a>
                            <?php
                            $position = get_field('position', $post->ID);
                            if( $position ): ?>
                                <p><?php echo $position->name; ?> </p>
                            <?php endif; ?>
                            <a href="mailto:<?php the_field('e-mail', $post->ID) ?>"><?php the_field('e-mail', $post->ID) ?></a>
                        </div>
                    <?php endforeach; ?>
                    <?php wp_reset_postdata(); ?>
                </div>
            <?php endif; ?>


            <?php
            $posts = get_posts(array(
                'posts_per_page'	=> -1,
                'post_type'			=> 'lawyers',
                'suppress_filters'  => 0,
                'meta_query' => array(
                    array(
                        'key' => 'position',
                        'value' => '15',
                        'compare' => 'LIKE'
                    )
                )
            ));
            if( $posts ): ?>
                <h1> <?php _e( 'Research Assistants', 'btp-cm' ) ?> </h1>

                <div id="btp-team">
                    <?php foreach( $posts as $post ):
                        setup_postdata( $post );
                        ?>
                        <div class="lawyer-id-team">
                            <?php if( get_field('portrait', $post->ID) ): ?>
                            <a href=' <?php echo get_the_permalink($post->ID); ?>'>
                                <img src="<?php the_field('portrait', $post->ID); ?>" />
                                <?php endif; ?>
                                <p class="lawyer-name-team">
                                    <?php the_field('vorname', $post->ID)?>
                                    <?php the_field('nachname', $post->ID) ?>
                                </p></a>
                            <?php
                            $position = get_field('position', $post->ID);
                            if( $position ): ?>
                                <p><?php echo $position->name; ?> </p>
                            <?php endif; ?>
                            <a href="mailto:<?php the_field('e-mail', $post->ID) ?>"><?php the_field('e-mail', $post->ID) ?></a>
                        </div>
                    <?php endforeach; ?>
                    <?php wp_reset_postdata(); ?>
                </div>
            <?php endif; ?>

            </div>

            <?php wp_reset_postdata(); ?>


    </section>
<?php
}
//
/*   <a class="publication-pagination-btn" data-site="<?php echo $site === 1 ? 1 : $site - 1 ?>">previous site</a>*/
/*    <a class="publication-pagination-btn" data-site="<?php echo $site + 1 ?>">next site</a>*/
?>

