<section class="cm-page">





<h1>Publication Manager</h1>


<div class="box-wrapper">
    <ul class="big-box-list">
        <li class="big-box-item">
            <div class="big-box-content">
                <h3><span class="dashicons dashicons-businessman"></span> Autoren</h3>
                <p>Erstellen und verwalten Sie Autoren.</p>
                <a href="edit.php?post_type=lawyers">Weiter zu den Autoren</a>
            </div>
        </li>
        <li class="big-box-item">
            <div class="big-box-content">
                <h3><span class="dashicons dashicons-book-alt"></span> Verläge</h3>
                <p>Erstellen und verwalten Sie Verläge.</p>
                <a href="edit.php?post_type=publisher">Weiter zu den Verlägen</a>
            </div>
        </li>
    </ul>
    <ul class="small-box-list">
        <li class="small-box-item">
            <div class="small-box-content">
                <h3><span class="dashicons dashicons-book"></span> Bücher</h3>
                <p>Erstellen und verwalten Sie Bücher.</p>
                <a href="edit.php?post_type=books">Weiter zu den Büchern</a>
            </div>
        </li>
        <li class="small-box-item">
            <div class="small-box-content">
                <h3><span class="dashicons dashicons-testimonial"></span> Beiträge</h3>
                <p>Erstellen und verwalten Sie Beiträge.</p>
                <a href="edit.php?post_type=articles">Weiter zu den Beiträgen</a>
            </div>
        </li>
        <li class="small-box-item">
            <div class="small-box-content">
                <h3><span class="dashicons dashicons-admin-page"></span> Publikationen</h3>
                <p>Erstellen und verwalten Sie Publikationen.</p>
                <a href="edit.php?post_type=publications">Weiter zu den Publikationen</a>
            </div>
        </li>
    </ul>
</div>

</section>