<?php
/**
 * Created by PhpStorm.
 * User: max
 * Date: 11.10.18
 * Time: 10:52
 */
$authors = getAuthorsList();
$verlage = getVerlageList();
$mode = isset($_GET['mode']) ? $_GET['mode'] : '';

if((isset($_GET['action']) && $_GET['action'] === 'create') && (isset($_POST['submit']) && $_POST['submit'] === 'Submit')){
    switch($mode){
        case 'authors':
            createAuthor();
            break;
        case 'books':
            createBook();
            break;
        case 'articles':
            createArticle();
            break;
        case 'publications':
            createPublication();
            break;
        case 'verlaege':
            createVerlag();
            break;
    }
}


?>
<div class="authors-section create-section ">
    <h2 class="create-toggle"><?php _e('Authors'); ?> <span class="dashicons dashicons-arrow-<?= $mode === 'authors' ? 'down' : 'right' ?>-alt2"></span></h2>
    <div class="authors-form-wrapper form-wrapper <?= $mode === 'authors' ? '' : 'hidden' ?>">
        <form class="pm-create-form" action="admin.php?page=create&mode=authors&action=create" method="POST">
            <div class="form-group">
                <?php echo Formbuilder::addInput("title", "text", "author-input", "title-input", "Title"); ?>
            </div>
            <div class="form-group">
                <?php echo Formbuilder::addInput("firstname", "text", "author-input", "firstname-input", "First Name *"); ?>
            </div>
            <div class="form-group">
                <?php echo Formbuilder::addInput("lastname", "text", "author-input", "lastname-input", "Last Name *"); ?>
            </div>
            <div class="form-group">
                <?php echo Formbuilder::addInput("submit", "submit", "author-button", "submit_authors", null, "Submit"); ?>
            </div>
        </form>
    </div>
</div>

<div class="books-section create-section">
    <h2 class="create-toggle"><?php _e('Books'); ?> <span class="dashicons dashicons-arrow-<?= $mode === 'books' ? 'down' : 'right' ?>-alt2"></span></h2>
    <div class="books-form-wrapper form-wrapper <?= $mode === 'books' ? '' : 'hidden' ?>">
        <form class="pm-create-form" action="admin.php?page=create&mode=books&action=create" method="POST">
            <div class="form-group">
                <?php echo Formbuilder::addInput("title", "text", "books-input", "title-input", "Titel"); ?>
            </div>
            <div class="form-group">
            <?php
            $authorsSelect = [];
            foreach($authors as $a){
                array_push($authorsSelect, ['value' => $a['ID'], 'text' => $a['title'] . " " . $a['firstname'] . " " .$a['lastname'] ]);
            }
            echo Formbuilder::addSelect($authorsSelect, "author", null, "Author");
            ?>
            </div>
            <div class="form-group">
            <?php
            $verlageList = [];
            foreach($verlage as $v){
                array_push($verlageList, ['value' => $v['ID'], 'text' => $v['name']]);
            }
            echo Formbuilder::addSelect($verlageList,"verlag", null,"Verlag");
            ?>
            </div>

            <div class="form-group">
              <label for="upload_book_url"> <?php _e('PDF'); ?> <br></label>
                <?php echo Formbuilder::addInput("upload_book_url", "button", "file_upload_button", "1", null, "Upload book"); ?>
                <?php echo Formbuilder::addInput("url", "hidden", "url_value"); ?>
            </div>
            <div class="form-group">
                <?php echo Formbuilder::addInput("edition", "text", "publication-input", "edition-input", "Auflage"); ?>
            </div>
            <div class="form-group">
              <label for="upload_book_img"><?php _e('Thumbnail'); ?></label>
              <div class='image-preview-wrapper'>
            		<img class='image-preview' src='https://btp.at/btp-content/uploads/2017/08/pdf_sujet.jpg' width='100' height='100' style='max-height: 100px; width: 100px;'>
            	</div>
              <?php echo Formbuilder::addInput("upload_book_img", "button", "file_upload_button img-prev", "2", null, "Upload image"); ?>
              <?php echo Formbuilder::addInput("thumbnailUrl", "hidden", "url_value"); ?>

            </div>
            <div class="form-group">
                <?php echo Formbuilder::addInput("english", "checkbox", "pm-checkbox", null, "English", "isEnglish"); ?>
            </div>
            <div class="form-group">
                <?php echo Formbuilder::addInput("german", "checkbox", "pm-checkbox", null, "German", "isGerman"); ?>
            </div>
            <div class="form-group">
                <?php echo Formbuilder::addInput("submit", "submit", "publication-button", "submit_authors", null, "Submit"); ?>
            </div>
        </form>
    </div>
</div>

<div class="articles-section create-section">
    <h2 class="create-toggle"><?php _e('Articles'); ?> <span class="dashicons dashicons-arrow-<?= $mode === 'articles' ? 'down' : 'right' ?>-alt2"></span></h2>
    <div class="articles-form-wrapper form-wrapper <?= $mode === 'articles' ? '' : 'hidden' ?>">
        <form class="pm-create-form" action="admin.php?page=create&mode=articles&action=create" method="POST">
            <div class="form-group">
                <?php echo Formbuilder::addInput("title", "text", "books-input", "title-input", "Titel"); ?>
            </div>
            <div class="form-group">
            <?php
            $authorsSelect = [];
            foreach($authors as $a){
                array_push($authorsSelect, ['value' => $a['ID'], 'text' => $a['title'] . " " . $a['firstname'] . " " .$a['lastname'] ]);
            }
            echo Formbuilder::addSelect($authorsSelect, "author", null, "Author");
            ?>
            </div>
            <div class="form-group">
            <?php
            $verlageList = [];
            foreach($verlage as $v){
                array_push($verlageList, ['value' => $v['ID'], 'text' => $v['name']]);
            }
            echo Formbuilder::addSelect($verlageList,"verlag", null,"Verlag");
            ?>
            </div>
            <div class="form-group">
              <label for="upload_book_img"><?php _e('Thumbnail'); ?></label>
              <div class='image-preview-wrapper'>
                <img class='image-preview' src='https://btp.at/btp-content/uploads/2017/08/pdf_sujet.jpg' width='100' height='100' style='max-height: 100px; width: 100px;'>
              </div>
              <?php echo Formbuilder::addInput("upload_article_img", "button", "file_upload_button img-prev", "3", null, "Upload image"); ?>
              <?php echo Formbuilder::addInput("thumbnailUrl", "hidden", "url_value"); ?>

            </div>
            <div class="form-group">
              <label for="upload_book_url"> <?php _e('PDF'); ?> <br></label>
                <?php echo Formbuilder::addInput("upload_article_url", "button", "file_upload_button", "4", null, "Upload article"); ?>
                <?php echo Formbuilder::addInput("url", "hidden", "url_value"); ?>
            </div>
            <div class="form-group">
                <label for="date"><span class="form-group-label"><?php _e('Date'); ?></span>
                    <input type="date" name="date" />
                </label>
            </div>
            <div class="form-group">
                <?php echo Formbuilder::addInput("english", "checkbox", "pm-checkbox", null, "English", "isEnglish"); ?>
            </div>
            <div class="form-group">
                <?php echo Formbuilder::addInput("german", "checkbox", "pm-checkbox", null, "German", "isGerman"); ?>
            </div>
            <div class="form-group">
                <?php echo Formbuilder::addInput("submit", "submit", "publication-button", "submit_authors", null, "Submit"); ?>
            </div>
        </form>
    </div>
</div>

<div class="publications-section create-section">
    <h2 class="create-toggle"><?php _e('Publications'); ?> <span class="dashicons dashicons-arrow-<?= $mode === 'publications' ? 'down' : 'right' ?>-alt2"></span></h2>
    <div class="publications-form-wrapper form-wrapper <?= $mode === 'publications' ? '' : 'hidden' ?>">
        <form class="pm-create-form" action="admin.php?page=create&mode=publications&action=create" method="POST">
            <div class="form-group">
                <?php echo Formbuilder::addInput("title", "text", "publication-input", "title-input", "Titel"); ?>
            </div>
            <div class="form-group">
            <?php
            $authorsSelect = [];
            foreach($authors as $a){
                array_push($authorsSelect, ['value' => $a['ID'], 'text' => $a['title'] . " " . $a['firstname'] . " " .$a['lastname'] ]);
            }
            echo Formbuilder::addSelect($authorsSelect, "author", null, "Author");
            ?>
            </div>
            <div class="form-group">
                <?php
            $verlageList = [];
            foreach($verlage as $v){
                array_push($verlageList, ['value' => $v['ID'], 'text' => $v['name']]);
            }
            echo Formbuilder::addSelect($verlageList,"verlag", null,"Verlag");
            ?>
            </div>
            <div class="form-group">
                <label for="date"><span class="form-group-label"><?php _e('Date'); ?></span>
                    <input type="date" name="date" />
                </label>
            </div>
            <div class="form-group">
              <label for="upload_book_img"><?php _e('Thumbnail'); ?></label>
              <div class='image-preview-wrapper'>
                <img class='image-preview' src='https://btp.at/btp-content/uploads/2017/08/pdf_sujet.jpg' width='100' height='100' style='max-height: 100px; width: 100px;'>
              </div>
              <?php echo Formbuilder::addInput("upload_publication_img", "button", "file_upload_button img-prev", "5", null, "Upload image"); ?>
              <?php echo Formbuilder::addInput("thumbnailUrl", "hidden", "url_value"); ?>

            </div>
            <div class="form-group">
              <label for="upload_book_url"> <?php _e('PDF'); ?> <br></label>
                <?php echo Formbuilder::addInput("upload_publication_url", "button", "file_upload_button", "6", null, "Upload publication"); ?>
                <?php echo Formbuilder::addInput("url", "hidden", "url_value"); ?>
            </div>
            <div class="form-group">
                <?php echo Formbuilder::addInput("english", "checkbox", "pm-checkbox", null, "English", "isEnglish"); ?>
            </div>
            <div class="form-group">
                <?php echo Formbuilder::addInput("german", "checkbox", "pm-checkbox", null, "German", "isGerman"); ?>
            </div>
            <div class="form-group">
                <?php echo Formbuilder::addInput("submit", "submit", "publication-button", "submit_authors", null, "Submit"); ?>
            </div>

        </form>
    </div>
</div>

<div class="verlaege-section create-section">
    <h2 class="create-toggle"><?php _e('Publishers'); ?> <span class="dashicons dashicons-arrow-<?= $mode === 'verlaege' ? 'down' : 'right' ?>-alt2"></span></h2>
    <div class="verlaege-form-wrapper form-wrapper <?= $mode === 'verlaege' ? '' : 'hidden' ?>">
        <form class="pm-create-form" action="admin.php?page=create&mode=verlaege&action=create" method="POST">
            <div class="form-group">
                <?php echo Formbuilder::addInput("name", "text", "author-input", "name-input", "Name"); ?>
            </div>
            <div class="form-group">
                <?php echo Formbuilder::addInput("submit", "submit", "author-button", "submit_authors", null, "Submit"); ?>
            </div>
        </form>
    </div>
</div>
